### ISSUE TITLE
Does not use .reek configuration

### ISSUE THREAD

**Issue by pbstriker38** [mmozuras/pronto-reek#17]
`pronto run` does not use the .reek configuration file in the project directory. When reek is used directly it does use the config. How can I tell pronto-reek to use the reek config?

https://github.com/troessner/reek#configuration

**Comment by mmozuras** [comment]
Fixed by @zewelor [with this PR](https://github.com/mmozuras/pronto-reek/pull/16/files). 

Released with version [v0.7.1](https://github.com/mmozuras/pronto-reek/releases/tag/v0.7.1).
