### ISSUE TITLE
Breaks with reek v2.0.2

### ISSUE THREAD

**Issue by jeroenj** [mmozuras/pronto-reek#5]
It works fine on v2.0.1 but breaks on v2.0.2 with the following error:

```ruby
/Users/jeroen/.gem/ruby/2.2.0/gems/reek-2.0.2/lib/reek/core/smell_repository.rb:22:in `initialize': uninitialized constant Reek::Core::SmellRepository::Configuration (NameError)
```

I don't know exactly what causes the issues, but it appears that some related code might have changed: https://github.com/troessner/reek/compare/v2.0.1...v2.0.2. I'll try to have a deeper look at it when I find some time.

**Comment by mmozuras** [comment]
As the latest version works with `reek v2.2.1`, this is no longer relevant. Thanks for reporting :bow:

**Comment by jeroenj** [comment]
:+1: Tanks! :)
